import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const root = process.cwd();
const pkg = path.join(root, 'research/datasaudi-package-06-live-observation');
const read = p => JSON.parse(fs.readFileSync(path.join(root, p), 'utf8'));
const lines = p => fs.readFileSync(path.join(root, p), 'utf8').trim().split('\n').filter(Boolean).map(JSON.parse);
const sha = s => crypto.createHash('sha256').update(s).digest('hex');
const write = (p, v) => { const f=path.join(root,p); fs.mkdirSync(path.dirname(f),{recursive:true}); fs.writeFileSync(f, typeof v==='string'?v:JSON.stringify(v,null,2)+'\n'); };
const selected = lines('research/datasaudi-package-06-live-observation/01-campaign/selected-executions.jsonl');
const main = read('research/datasaudi-package-06-live-observation/02-runs/p06-live-20260715-main/run-end.json');
const probe = read('research/datasaudi-package-06-live-observation/02-runs/p06-live-20260715-probe/run-end.json');
const mainT = lines(main.transcript_path); const probeT = lines(probe.transcript_path);
const byExec = new Map(mainT.filter(x=>x.execution_id).map(x=>[x.execution_id,x]));
const obs = [];
for (const s of selected) {
  const t = s.execution_id ? byExec.get(s.execution_id) : probeT.find(x=>x.prompt_sha256===s.prompt_sha256);
  if (!t) continue;
  obs.push({schema_version:'1.0', campaign_question_id:s.campaign_question_id, execution_id:s.execution_id, legacy_id:s.legacy_id, mapping:s.mapping, run_id:t.run_id, status:t.status, attempted:true, prompt_sha256:s.prompt_sha256, answer_sha256:t.raw_answer_sha256||null, sent_at_utc:t.sent_at_utc, completed_at_utc:t.completed_at_utc||null, evidence:{transcript:t.run_id+'/transcripts.jsonl', history:t.history?.path||null}, stable_user_fingerprint_sha256:t.stable_user_fingerprint_sha256, raw_user_id_persisted:false, auth_token_persisted:false});
}
const quota = selected.find(s=>s.execution_id && !byExec.has(s.execution_id) && s.campaign_order===28);
if (quota) obs.push({schema_version:'1.0',campaign_question_id:quota.campaign_question_id,execution_id:quota.execution_id,legacy_id:null,mapping:quota.mapping,run_id:main.run_id,status:'QUOTA_BLOCKED',attempted:true,prompt_sha256:quota.prompt_sha256,answer_sha256:null,sent_at_utc:null,completed_at_utc:main.completed_at_utc,evidence:{run_end:'02-runs/p06-live-20260715-main/run-end.json'},stable_user_fingerprint_sha256:read('research/datasaudi-package-06-live-observation/00-governance/AUTHORITY.json').stable_user_fingerprint_sha256,raw_user_id_persisted:false,auth_token_persisted:false});
write('research/datasaudi-package-06-live-observation/03-observation-ledger/live-observations.jsonl', obs.map(x=>JSON.stringify(x)).join('\n')+'\n');
const adjud = obs.map(x=>({schema_version:'1.0',campaign_question_id:x.campaign_question_id,execution_id:x.execution_id,status:x.status==='OBSERVED_ANSWER'?'PENDING_INDEPENDENT_ADJUDICATION':x.status==='QUOTA_BLOCKED'?'NOT_ADJUDICATED_QUOTA':'SUPPLEMENTAL_OBSERVED_REFUSAL',observation_ref:'03-observation-ledger/live-observations.jsonl',judgment:null}));
write('research/datasaudi-package-06-live-observation/04-adjudication/adjudication.jsonl',adjud.map(x=>JSON.stringify(x)).join('\n')+'\n');
const counts={observed_answer:obs.filter(x=>x.status==='OBSERVED_ANSWER').length,quota_blocked:obs.filter(x=>x.status==='QUOTA_BLOCKED').length,supplemental_observed_refusal:obs.filter(x=>x.status==='OBSERVED_REFUSAL').length,pending_adjudication:adjud.filter(x=>x.status==='PENDING_INDEPENDENT_ADJUDICATION').length};
write('research/datasaudi-package-06-live-observation/04-adjudication/summary.json',{schema_version:'1.0',...counts,unique_mapped_live_cells:counts.observed_answer,baseline_p05_unique_live_cells:31,cumulative_unique_live_cells:31+counts.observed_answer,main_messages_attempted:main.attempted_count,probe_messages_attempted:probe.attempted_count,main_unsent:main.remaining_unsent_count,adjudication_policy:'Observation is not correctness; independent adjudication remains pending.'});
const authority=read('research/datasaudi-package-06-live-observation/00-governance/AUTHORITY.json');
const stableFingerprint=mainT.find(x=>x.stable_user_fingerprint_sha256)?.stable_user_fingerprint_sha256 || probeT.find(x=>x.stable_user_fingerprint_sha256)?.stable_user_fingerprint_sha256;
write('research/datasaudi-package-06-live-observation/SUMMARY.json',{schema_version:'1.0',package:'P06',status:'P06_LIVE_WINDOW_CLOSED_ON_QUOTA',completed_at_utc:main.completed_at_utc,baseline_p05:{reference_cells:2304,unique_live_observed:31},p06:{selected:30,main_selected:29,main_attempted:main.attempted_count,probe_attempted:probe.attempted_count,new_unique_observed:counts.observed_answer,quota_blocked:counts.quota_blocked,supplemental_refusal:counts.supplemental_observed_refusal,main_unsent:main.remaining_unsent_count},cumulative:{unique_live_observed:31+counts.observed_answer},stable_user_fingerprint_sha256:stableFingerprint,raw_user_id_persisted:false,auth_token_persisted:false,narrative:'A lawful same-identity live window added 26 mapped observations, then stopped at the platform quota. Two main executions remain unsent; no claim is made for them.'});
const checks=[['selected_count',selected.length===30],['main_attempted',main.attempted_count===27],['probe_attempted',probe.attempted_count===1],['answers',counts.observed_answer===26],['quota_stop',main.stopped_on_quota===true],['unsent',main.remaining_unsent_count===2],['unique_execs',new Set(obs.filter(x=>x.execution_id&&x.status==='OBSERVED_ANSWER').map(x=>x.execution_id)).size===26],['prompt_hashes',obs.every(x=>x.prompt_sha256)],['answer_hashes',obs.filter(x=>x.status==='OBSERVED_ANSWER').every(x=>x.answer_sha256)],['stable_identity',obs.every(x=>x.stable_user_fingerprint_sha256===stableFingerprint)],['no_raw_user_id',obs.every(x=>x.raw_user_id_persisted===false)],['no_auth_token',obs.every(x=>x.auth_token_persisted===false)],['adjudication_separate',adjud.length===obs.length],['baseline_preserved',31+counts.observed_answer===57]];
write('research/datasaudi-package-06-live-observation/VALIDATION.json',{schema_version:'1.0',status:checks.every(x=>x[1])?'PASS':'FAIL',checks_total:checks.length,checks_passed:checks.filter(x=>x[1]).length,checks:checks.map(([name,pass])=>({name,status:pass?'PASS':'FAIL'})),metrics:{selected:30,main_attempted:27,probe_attempted:1,observed_answer:26,quota_blocked:1,supplemental_refusal:1,unsent:2,cumulative_unique_live_cells:57}});
write('research/datasaudi-package-06-live-observation/CLOSEOUT.md','# Package 06 closeout\n\nThe lawful same-identity window completed 27 main attempts and stopped on quota after 26 answers. One supplemental P04-003 probe was refused. P05 remains the 31-cell baseline; P06 adds 26 mapped observations, for 57 cumulative unique live cells. Two selected main executions remain unsent. Observations and adjudication are intentionally separate; no correctness claim is made here.\n');
const files=[]; const walk=d=>{for(const n of fs.readdirSync(d)){const f=path.join(d,n); if(n==='PACKAGE_MANIFEST.json') continue; const st=fs.statSync(f); st.isDirectory()?walk(f):files.push(f)}}; walk(pkg); files.sort(); const entries=files.map(f=>({path:path.relative(root,f),bytes:fs.statSync(f).size,sha256:sha(fs.readFileSync(f))})); write('research/datasaudi-package-06-live-observation/PACKAGE_MANIFEST.json',{schema_version:'1.0',package:'P06',artifact_count:entries.length,tree_sha256:sha(entries.map(x=>`${x.path}\t${x.bytes}\t${x.sha256}`).join('\n')),artifacts:entries});
console.log(JSON.stringify({observations:obs.length,counts,validation:checks.filter(x=>x[1]).length+'/'+checks.length}));
